name: locust-envoy

services:
  master:
    image: locustio/locust:2.16.1
    external_links:
      - envoy
    command:
      --config /etc/envoy-example/locust/test-envoy.conf --master --run-time=60s
    volumes:
      - /tmp/envoy-example/locust:/etc/envoy-example/locust
    working_dir: /etc/envoy-example/locust
    networks:
      - envoy-example
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '1'
          memory: 32M

  worker:
    image: locustio/locust:2.16.1
    links:
      - master
    external_links:
      - envoy
    command:
      --config /etc/envoy-example/locust/test-envoy.conf --worker
    volumes:
      - /tmp/envoy-example/locust:/etc/envoy-example/locust
    working_dir: /etc/envoy-example/locust
    networks:
      - envoy-example
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '1'
          memory: 32M

networks:
  envoy-example:
    name: envoy-example
    driver: bridge
